name: Build & deploy project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Install dependencies
      run: yarn
    - name: Build vue
      run: yarn build
    - uses: actions/upload-artifact@v1
      with:
        name: release
        path: dist 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: release
          path: dist
      - name: Deploy FTP
        uses: sebastianpopp/ftp-action@master
        with:
          host: "${{ secrets.FTP_HOST }}"
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: "dist"
          remoteDir: "."
